name: run

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - 'OriginLists.txt'
  schedule:
      - cron: 30 18 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
        
    - name: Clone source lists
      run: wget -i OriginLists.txt
      
    - name: Cat all the files
      run: cat *.txt > Result.txt
      
    - name: DeDuplicate
      run: |
        chmod +x dedup.sh
        sudo ./dedup.sh
        
    - name: Dontblock
      run: |
        chmod +x dontblock.sh
        sudo ./dontblock.sh
        
    - name: Upload to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Result.txt
        tag: Auto
        overwrite: true
        file_glob: true
    - uses: ncipollo/release-action@v1
      with:
       tag: Auto
       allowUpdates: true
       name: lists
       token: ${{ secrets.GITHUB_TOKEN }}
